[wokwi]
version = 1
elf = "RPI_PICO_W-20250911-v1.26.1.uf2"
firmware = "RPI_PICO_W-20250911-v1.26.1.uf2"
rfc2217ServerPort = 4000  # Publisher on port 4000

[net]
gateway = "ws://localhost:9011"  # Wokwi gateway for WiFi/MQTT
